export default [
  {
    session_id: 1,
    pull_num_today: 1,
    pull_num_overall: 1,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "No tank swap on 1st TB",
    players_responsible: JSON.stringify(JSON.stringify(["Chro", "Sophia"])),
    log_link: "",
    clip_link: "",
    notes: "Next auto killed Chro → Chro exploded and killed 3 others",
  },
  {
    session_id: 1,
    pull_num_today: 2,
    pull_num_overall: 2,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "3 people killed by clone lines",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Sophia", "Char", "Laveera"])
    ),
    log_link: "",
    clip_link: "",
    notes:
      "TB killed both tanks again, but we recovered. Timing or precise positioning in the safe spots got Soph and both RDPS.",
  },
  {
    session_id: 1,
    pull_num_today: 3,
    pull_num_overall: 3,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "General mech-learning chaos",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Sophia", "Char"])
    ),
    log_link: "",
    clip_link: "",
    notes:
      "1) TB killed tanks; 2) Did not rez in time to see clones → late safe spot call → Quil, Tori, Ruv, and Laveera died to clone lines; 3) Char too close to Ella",
  },
  {
    session_id: 1,
    pull_num_today: 4,
    pull_num_overall: 4,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Char & Chro clone lines + Sophia mit",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Sophia", "Char"])
    ),
    log_link: "",
    clip_link: "",
    notes:
      "Soph had no mit on the TB's secondary explosion and got overkilled by 6.5k",
  },
  {
    session_id: 1,
    pull_num_today: 5,
    pull_num_overall: 5,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "¾ of group 1 thought it was stack",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Ruv", "Quil"])
    ),
    log_link: "",
    clip_link: "",
    notes: "spoilers: it was spread",
  },
  {
    session_id: 1,
    pull_num_today: 6,
    pull_num_overall: 6,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Late tank swap + Laveera too close on lightning spreads",
    players_responsible: JSON.stringify(JSON.stringify(["Sophia", "Laveera"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 7,
    pull_num_overall: 7,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "First time seeing tethers = 4 people got burnt struck",
    players_responsible: JSON.stringify(
      JSON.stringify(["Sophia", "Ruv", "Laveera", "Char"])
    ),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 8,
    pull_num_overall: 8,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "6/2 memes",
    players_responsible: JSON.stringify(JSON.stringify(["Chro", "Laveera"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 9,
    pull_num_overall: 9,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: '"Spread... Was it spread?"',
    players_responsible: JSON.stringify([]),
    log_link: "",
    clip_link: "",
    notes:
      "NOPE. Stack targeted tanks, so it only caught them + the healers in the AoE. Healers overkilled by 27k with shields + 10% mit, so a HEAVILY mitted 2-stack or a 3-stack is probably survivable.",
  },
  {
    session_id: 1,
    pull_num_today: 10,
    pull_num_overall: 10,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Char hit by clone lines",
    players_responsible: JSON.stringify(JSON.stringify(["Char"])),
    log_link: "",
    clip_link: "",
    notes: "Dead person → proteans double up on someone else",
  },
  {
    session_id: 1,
    pull_num_today: 11,
    pull_num_overall: 11,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Char & Ella got burnt struck",
    players_responsible: JSON.stringify(JSON.stringify(["Ella", "Char"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 12,
    pull_num_overall: 12,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "We went B/D but safe was 1/3",
    players_responsible: JSON.stringify(JSON.stringify(["Ruv", "Char"])),
    log_link: "",
    clip_link: "",
    notes:
      "Laveera/Tori (1/3) stayed at their walls, but so did Char/Ruv (B/D), so there was lots of confusion.",
  },
  {
    session_id: 1,
    pull_num_today: 13,
    pull_num_overall: 13,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "6/2 memes",
    players_responsible: JSON.stringify(JSON.stringify(["Sophia", "Char"])),
    log_link: "",
    clip_link: "",
    notes:
      "Soph and Char went to A, realized they should be C, but didn't have time to fix it",
  },
  {
    session_id: 1,
    pull_num_today: 14,
    pull_num_overall: 14,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Most of the raid got KBed into wall",
    players_responsible: JSON.stringify([
      "Chro",
      "Sophia",
      "Ruv",
      "Ella",
      "Quil",
      "Tori",
    ]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 15,
    pull_num_overall: 15,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Lightning spreads",
    players_responsible: JSON.stringify(JSON.stringify(["Chro", "Char"])),
    log_link: "",
    clip_link: "",
    notes:
      "Both just a smidge too close to their healers. Chro was on the 2nd ring from mid, instead of the innermost",
  },
  {
    session_id: 1,
    pull_num_today: 16,
    pull_num_overall: 16,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "TB mitigation",
    players_responsible: JSON.stringify(JSON.stringify(["Chro"])),
    log_link: "",
    clip_link: "",
    notes: "686,783 damage vs. 19% mitigation... who will win?",
  },
  {
    session_id: 1,
    pull_num_today: 17,
    pull_num_overall: 17,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Both healers KBed into wall",
    players_responsible: JSON.stringify(JSON.stringify(["Ruv", "Ella"])),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/BusyFrigidBeanGrammarKing-D5uyO6HINEQbjrVt",
    notes: "can we talk about this clip though?",
  },
  {
    session_id: 1,
    pull_num_today: 18,
    pull_num_overall: 18,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "More wall KBs",
    players_responsible: JSON.stringify(JSON.stringify(["Ella", "Quil"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 19,
    pull_num_overall: 19,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Yet more wall KBs",
    players_responsible: JSON.stringify(JSON.stringify(["Chro", "Ella"])),
    log_link: "",
    clip_link: "",
    notes:
      "tbf, Chro was flexing for the first time. I, however, have no excuse",
  },
  {
    session_id: 1,
    pull_num_today: 20,
    pull_num_overall: 20,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "You guessed it, more wall KBs",
    players_responsible: JSON.stringify(JSON.stringify(["Ella"])),
    log_link: "",
    clip_link: "",
    notes:
      "But at least we got a glimpse of tethers! Sidenote: Laveera died to protean damage. He outranged 2 shields and just BARELY missed Kera (srsly like 30.0001 yalms), so he wasn't topped. This is downtime, so we could do a combination of Laveera staying mid a sec longer + healers using single-target stuff to let the man paint in peace",
  },
  {
    session_id: 1,
    pull_num_today: 21,
    pull_num_overall: 21,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "Laveera too close on lightning clocks",
    players_responsible: JSON.stringify(JSON.stringify(["Laveera"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 22,
    pull_num_overall: 22,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Ella wall KB → no shields on Burnished Glory",
    players_responsible: JSON.stringify(JSON.stringify(["Ella"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 23,
    pull_num_overall: 23,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "ella kb wall whyyyyyyyyyyyyyyyyy",
    players_responsible: JSON.stringify(JSON.stringify(["Ella"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 24,
    pull_num_overall: 24,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Sophia and Ella wall KB",
    players_responsible: JSON.stringify(JSON.stringify(["Sophia", "Ella"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 25,
    pull_num_overall: 25,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "MY TOE",
    players_responsible: JSON.stringify(JSON.stringify(["Ella"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 26,
    pull_num_overall: 26,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "You can tell it was our first time actually doing the mech",
    players_responsible: JSON.stringify([]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2312093293?t=00h17m00s",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 27,
    pull_num_overall: 27,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Ella and Tori got blasted",
    players_responsible: JSON.stringify(JSON.stringify(["Ella", "Tori"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 28,
    pull_num_overall: 28,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Chro and Ruv too close for lightning spreads",
    players_responsible: JSON.stringify(JSON.stringify(["Chro", "Ruv"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 29,
    pull_num_overall: 29,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "We need a mit plan",
    players_responsible: JSON.stringify([]),
    log_link: "",
    clip_link: "",
    notes: "Raw dogged tethers 1 -3, literally no one mitigated lmao",
  },
  {
    session_id: 1,
    pull_num_today: 30,
    pull_num_overall: 30,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Tori and Ruv overlapped lightning baits",
    players_responsible: JSON.stringify(JSON.stringify(["Ruv", "Tori"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 31,
    pull_num_overall: 31,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Soph baited fire on the other party",
    players_responsible: JSON.stringify(JSON.stringify(["Sophia"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 32,
    pull_num_overall: 32,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Chro late getting to fire stack",
    players_responsible: JSON.stringify(JSON.stringify(["Chro"])),
    log_link: "",
    clip_link: "",
    notes:
      "Chro ran in very close to Laveera (the tether) and baited the cone S, making it a 2-stack. So, technically, he did make it to the stack in time!",
  },
  {
    session_id: 1,
    pull_num_today: 33,
    pull_num_overall: 33,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Ruv wrong side",
    players_responsible: JSON.stringify(JSON.stringify(["Ruv"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 34,
    pull_num_overall: 34,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Ella ate proteans; Soph and Char wall KB",
    players_responsible: JSON.stringify(
      JSON.stringify(["Sophia", "Ella", "Char"])
    ),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/LivelyHeadstrongFungusCopyThis-2SbKcQj3jbo7ePiw",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 35,
    pull_num_overall: 35,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Char wrong side — caller curse",
    players_responsible: JSON.stringify(JSON.stringify(["Char"])),
    log_link: "",
    clip_link: "",
    notes: "Got 3rd tether but took it east",
  },
  {
    session_id: 1,
    pull_num_today: 36,
    pull_num_overall: 36,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Char & Sophia wrong side",
    players_responsible: JSON.stringify(JSON.stringify(["Sophia", "Char"])),
    log_link: "",
    clip_link: "",
    notes:
      "Caller curse strikes again. Char took 3rd tether east; Soph needed to fill west since G1 got 3 tethers",
  },
  {
    session_id: 1,
    pull_num_today: 37,
    pull_num_overall: 37,
    phase: 1,
    mech: "Towers",
    prog_point_reached: "target",
    cause: "First time seeing towers!",
    players_responsible: JSON.stringify(
      JSON.stringify(["Ruv", "Tori", "Char"])
    ),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/SecretivePricklyCakeTooSpicy-jlnhBo3BFuIThmTC",
    notes:
      "Char burnt strike; Ruv wrong tower; Tori late. Also, everyone N blew up because Tori ended up being closer to Chro than Soph, so he got targeted for the TB explosion.",
  },
  {
    session_id: 1,
    pull_num_today: 38,
    pull_num_overall: 38,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Chro & Ruv lightning spreads",
    players_responsible: JSON.stringify(JSON.stringify(["Chro", "Ruv"])),
    log_link: "",
    clip_link: "",
    notes: "Chro tiny bit too far back, Ruv tiny bit too far forward",
  },
  {
    session_id: 1,
    pull_num_today: 39,
    pull_num_overall: 39,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Ella lightning spread (new spots)",
    players_responsible: JSON.stringify(JSON.stringify(["Ella"])),
    log_link: "",
    clip_link: "",
    notes:
      "This is the pull where we switched to healers on point. I wasn't on the innermost ring.",
  },
  {
    session_id: 1,
    pull_num_today: 40,
    pull_num_overall: 40,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Chro late to stack",
    players_responsible: JSON.stringify(JSON.stringify(["Chro"])),
    log_link: "",
    clip_link: "",
    notes:
      "3-stacks are usually survivable... unless you already have 1 stack of Mark of Mortality from fucked-up stacks on the mech before this.",
  },
  {
    session_id: 1,
    pull_num_today: 41,
    pull_num_overall: 41,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Laveera wrong side",
    players_responsible: JSON.stringify(JSON.stringify(["Laveera"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 42,
    pull_num_overall: 42,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "33% with 4 DDs and 2 deaths",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Sophia", "Laveera"])
    ),
    log_link: "",
    clip_link: "",
    notes:
      "First clean FoF! Laveera got DD from proteans; Soph wall KBed so Ruv, Quil, and Laveera got DDs (Laveera now at -99% lul); Chro got DD from Burnt Strike; tanks too close during final TB.",
  },
  {
    session_id: 1,
    pull_num_today: 43,
    pull_num_overall: 43,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Tori late to stack; Ella wrong spot",
    players_responsible: JSON.stringify(JSON.stringify(["Ella", "Tori"])),
    log_link: "",
    clip_link: "",
    notes:
      "Tori baited the cone on himself while running there; Ella should have been S.",
  },
  {
    session_id: 1,
    pull_num_today: 44,
    pull_num_overall: 44,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "16.5% with 3 DDs and 3 deaths",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Sophia", "Ruv"])
    ),
    log_link: "https://www.fflogs.com/reports/Fn6zbtjc2hLpVN9M#fight=48",
    clip_link: "",
    notes:
      "Ruv started FoF on wrong side and died trying to correct it → 3-stack put DDs on Quil, Soph, and Ella; tanks too close for final TB.",
  },
  {
    session_id: 1,
    pull_num_today: 45,
    pull_num_overall: 45,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Chro got blasted → people died on proteans",
    players_responsible: JSON.stringify(JSON.stringify(["Chro"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 46,
    pull_num_overall: 46,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Most cursed pattern: all tethers G1",
    players_responsible: JSON.stringify(JSON.stringify(["Sophia"])),
    log_link: "",
    clip_link: "",
    notes:
      "Tori and Soph were flexing and both went south. With all of G1 out of the picture, Sophia was, surprisingly, the outermost player on west side.",
  },
  {
    session_id: 1,
    pull_num_today: 47,
    pull_num_overall: 47,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Laveera wrong side",
    players_responsible: JSON.stringify(JSON.stringify(["Laveera"])),
    log_link: "",
    clip_link: "",
    notes: "Laveera quickly smudged to east side, but R1 always fills west.",
  },
  {
    session_id: 1,
    pull_num_today: 48,
    pull_num_overall: 48,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Laveera wrong side",
    players_responsible: JSON.stringify(JSON.stringify(["Laveera"])),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 1,
    pull_num_today: 49,
    pull_num_overall: 49,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "19% with 10 DDs and 2 deaths",
    players_responsible: JSON.stringify(
      JSON.stringify(["Chro", "Sophia", "Ella", "Quil"])
    ),
    log_link: "",
    clip_link: "",
    notes:
      "Only 2 DDs happened before towers: Ella proteans, Quil proteans + burnt strike. Everything else happened in the last 20 seconds. Tanks were too close for final TB, and Quil left the tower early.",
  },
  {
    session_id: 2,
    pull_num_today: 1,
    pull_num_overall: 50,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Char burnt strike; Hypatia wall KB",
    players_responsible: JSON.stringify(["Hypatia", "Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 2,
    pull_num_overall: 51,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "Ranged DPS too close on spreads",
    players_responsible: JSON.stringify(["Char", "Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 3,
    pull_num_overall: 52,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "All of group 1 walked in during clones",
    players_responsible: JSON.stringify(["Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "Safe lane was 1/3",
  },
  {
    session_id: 2,
    pull_num_today: 4,
    pull_num_overall: 53,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Heal plan in progress",
    players_responsible: JSON.stringify(["Ruv", "Ella"]),
    log_link: "test",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 5,
    pull_num_overall: 54,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: '"Uh, spread or stack?"',
    players_responsible: [],
    log_link: "",
    clip_link: "",
    notes: "One group guessed stack, the other guessed spread!",
  },
  {
    session_id: 2,
    pull_num_today: 6,
    pull_num_overall: 55,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Laveera thought he had a tether",
    players_responsible: JSON.stringify(["Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 7,
    pull_num_overall: 56,
    phase: 1,
    mech: "Towers",
    prog_point_reached: "target",
    cause: "South to north fill is hard",
    players_responsible: JSON.stringify(["Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 8,
    pull_num_overall: 57,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause: "FIRST P2!",
    players_responsible: JSON.stringify([""]),
    log_link:
      "https://www.twitch.tv/xelahart/clip/GlamorousZealousWebPeteZarollTie-kdKCNDNnajEdJbmh",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/AffluentFurtiveRhinocerosMau5-nTseP-62sHsjPfWM",
    notes: "Laveera and Ruv are GAMING and did everything right",
  },
  {
    session_id: 2,
    pull_num_today: 9,
    pull_num_overall: 58,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "Ella DD from proteans; Laveera scuffed opener",
    players_responsible: JSON.stringify(["Ella", "Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 10,
    pull_num_overall: 59,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Char burnt strike; Ruv wrong safe side",
    players_responsible: JSON.stringify(["Ruv", "Char"]),
    log_link: "",
    clip_link: "",
    notes: '"Ruv, your other fire"',
  },
  {
    session_id: 2,
    pull_num_today: 11,
    pull_num_overall: 60,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Ella ate a protean and then a burnt strike",
    players_responsible: JSON.stringify(["Ella"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 12,
    pull_num_overall: 61,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Fire cone got baited askew; actually not clear what happened here",
    players_responsible: JSON.stringify([""]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=00h40m35s",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 13,
    pull_num_overall: 62,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "WALL IS SAFE",
    players_responsible: JSON.stringify(["Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 14,
    pull_num_overall: 63,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      'Stars got coned. We started saying "calls are for cones" after this pull.',
    players_responsible: JSON.stringify(["Quil", "Hypatia", "Char", "Laveera"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/FaithfulDreamyChowderM4xHeh-re7BT3gP0vP4-QdR",
    notes:
      "Char and Hypatia responded to the cone call and were on intercards. Quil was on D, but she hugged boss and got coned. Also, don't think Laveera was far enough out with his star. ",
  },
  {
    session_id: 2,
    pull_num_today: 15,
    pull_num_overall: 64,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Char, Quil, and Laveera axe kick; Hypatia icicle; Ella star lines; Chro rotated CW",
    players_responsible: JSON.stringify([
      "Chro",
      "Ella",
      "Quil",
      "Hypatia",
      "Char",
      "Laveera",
    ]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/FragileFitAntelopeDAESuppy-vQA8R044GF92A0kH",
    notes: "First time seeing axe. IT'S REALLY REALLY FAR OUT",
  },
  {
    session_id: 2,
    pull_num_today: 16,
    pull_num_overall: 65,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "New tether prio growing pains",
    players_responsible: JSON.stringify(["Hypatia"]),
    log_link: "",
    clip_link: "",
    notes:
      'No swap was needed with our new "fixed, except when it isn\'t" strat. Hypatia flexed north like you would for actual fixed tethers',
  },
  {
    session_id: 2,
    pull_num_today: 17,
    pull_num_overall: 66,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Char didn't make it to safe spot",
    players_responsible: JSON.stringify(["Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 18,
    pull_num_overall: 67,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "Towers: Char moved out early; Hypatia wrong fill",
    players_responsible: JSON.stringify(["Hypatia", "Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 19,
    pull_num_overall: 68,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "Hypatia slightly late to stack = misaligned cone bait = DDs",
    players_responsible: JSON.stringify(["Hypatia"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/mega_quilava/clip/AmusedDepressedDonutJonCarnage-V_IgiibFttmGvwAl",
    notes: "I'd apologize to the PF dancers but they can't read",
  },
  {
    session_id: 2,
    pull_num_today: 20,
    pull_num_overall: 69,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "BG heals",
    players_responsible: JSON.stringify(["Ruv", "Ella"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 21,
    pull_num_overall: 70,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "Ella repair",
    players_responsible: JSON.stringify(["Ella"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 22,
    pull_num_overall: 71,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause: "Ruv thought he was cone",
    players_responsible: JSON.stringify(["Ruv"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/PerfectFrigidCobblerBrokeBack-qh0i6tn_zZ5HQfRL",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 23,
    pull_num_overall: 72,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "idk",
    players_responsible: JSON.stringify([""]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 24,
    pull_num_overall: 73,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause: "Ella too slow to get in after axe; Hypatia and Laveera star lines",
    players_responsible: JSON.stringify(["Ella", "Hypatia", "Laveera"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/ImpartialYawningPonyArsonNoSexy-6hX5o-9smtRqy8Gm",
    notes: "Also, cursed pattern",
  },
  {
    session_id: 2,
    pull_num_today: 25,
    pull_num_overall: 74,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Char took 3rd tether east",
    players_responsible: JSON.stringify(["Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 26,
    pull_num_overall: 75,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Ella & Char axe kick; Chro icicle; Quil dropped star on ring instead of wall",
    players_responsible: JSON.stringify(["Chro", "Ella", "Quil", "Char"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/CourageousRelatedClintmullinsFunRun-1j_AQ_caBAF4YPzU",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 27,
    pull_num_overall: 76,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Laveera solo baited cone",
    players_responsible: JSON.stringify(["Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 28,
    pull_num_overall: 77,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Ella & Chro axe kicked but survived; Quil knocked into star line; Chro rotated CW",
    players_responsible: JSON.stringify(["Chro", "Ella", "Quil"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/RenownedCleverBobaSMOrc-TpSWo-nP__U2ySlY",
    notes: "The wall Shiva jebait",
  },
  {
    session_id: 2,
    pull_num_today: 29,
    pull_num_overall: 78,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Char wrong side (tether 3)",
    players_responsible: JSON.stringify(["Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 30,
    pull_num_overall: 79,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Ella took Char's bait because she was too far in and Char was too far out",
    players_responsible: JSON.stringify(["Ella", "Char"]),
    log_link:
      "https://www.fflogs.com/reports/4W9pdzBFkvZn8CGc#fight=30&type=damage-taken&view=events&start=6492524&end=6550912",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/AmericanSlipperyHerringFutureMan-itiWzjInhx7L_ilv",
    notes:
      "Ruv thought he moved too quickly on puddles, but G1 just got doubled after most of G2 was dead. See logs, Sophia doesn't take a hit at 3:39 but G1 takes 2",
  },
  {
    session_id: 2,
    pull_num_today: 31,
    pull_num_overall: 80,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Ella & Quil axe kick; Quil moved in a sec too fast with star;  Hypatia wrong clock",
    players_responsible: JSON.stringify(["Ella", "Quil", "Hypatia"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/SmallAlluringGullOSkomodo-L2bufK1vAee3iiE3",
    notes: "Took star to intercard when first icicles were intercard",
  },
  {
    session_id: 2,
    pull_num_today: 32,
    pull_num_overall: 81,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "Hypatia DD and suicide",
    players_responsible: JSON.stringify(["Hypatia"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 33,
    pull_num_overall: 82,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "idk, lightning spreads",
    players_responsible: JSON.stringify([""]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 34,
    pull_num_overall: 83,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Char axe kick; Ruv wrong clock; Laveera & Hypatia didn't get in fast enough and got icicled; Char KB angle slightly off",
    players_responsible: JSON.stringify(["Ruv", "Hypatia", "Char", "Laveera"]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=02h13m20s",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 35,
    pull_num_overall: 84,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Char and Hypatia rotated towards Shiva; G1 died to damage/undermitting",
    players_responsible: JSON.stringify(["Hypatia", "Char"]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=02h17m45s",
    notes:
      "We had only shields, Troub, and then a late Holos + HoL, neither of which reached the opposite group. We should follow Char's Troub timing because it seems perfect. I think he used it just as we were getting KBed?",
  },
  {
    session_id: 2,
    pull_num_today: 36,
    pull_num_overall: 85,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Chro stacked on lightning",
    players_responsible: JSON.stringify(["Chro"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 37,
    pull_num_overall: 86,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause: "Stars didn't move out quickly enough",
    players_responsible: JSON.stringify(["Hypatia", "Char"]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=02h27m28s",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 38,
    pull_num_overall: 87,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Laveera missed shield",
    players_responsible: JSON.stringify(["Ella", "Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 39,
    pull_num_overall: 88,
    phase: 1,
    mech: "Utopian Sky",
    prog_point_reached: "target",
    cause: "Quil stacked with lightning",
    players_responsible: JSON.stringify(["Quil"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 40,
    pull_num_overall: 89,
    phase: 1,
    mech: "Towers",
    prog_point_reached: "target",
    cause: "Chro too close to group --> TB explosion targeted Quil",
    players_responsible: JSON.stringify(["Chro"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 41,
    pull_num_overall: 90,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Laveera and Char axe kick; Ella didn't get star all the way to the wall",
    players_responsible: JSON.stringify(["Ella", "Char", "Laveera"]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=02h38m45s",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 42,
    pull_num_overall: 91,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause: "Ella forgot where 3 is; Quil rotated wrong direction",
    players_responsible: JSON.stringify(["Ella", "Quil"]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=02h43m17s",
    notes:
      "That 3-stack lived longer than expected. Had shields, Troub, Barrier, and Holos, so that's prob a good amount of mit.",
  },
  {
    session_id: 2,
    pull_num_today: 43,
    pull_num_overall: 92,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "Char too close to Sophia on clock spread",
    players_responsible: JSON.stringify(["Char"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 44,
    pull_num_overall: 93,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Quil adjusted ",
    players_responsible: JSON.stringify(["Quil"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 45,
    pull_num_overall: 94,
    phase: 2,
    mech: "Diamond Dust",
    prog_point_reached: "newphase",
    cause:
      "Char and Hypatia too close to boss, Chro not close enough for cone bait",
    players_responsible: JSON.stringify(["Chro", "Hypatia", "Char"]),
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/2318554836?t=02h51m50s",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 46,
    pull_num_overall: 95,
    phase: 1,
    mech: "Fall of Faith",
    prog_point_reached: "target",
    cause: "Surprise fourth tether!",
    players_responsible: JSON.stringify(["Laveera"]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 47,
    pull_num_overall: 96,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "idk",
    players_responsible: JSON.stringify([""]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 48,
    pull_num_overall: 97,
    phase: 1,
    mech: "Opener",
    prog_point_reached: "target",
    cause: "idk",
    players_responsible: JSON.stringify([""]),
    log_link: "",
    clip_link: "",
    notes: "",
  },
  {
    session_id: 2,
    pull_num_today: 49,
    pull_num_overall: 98,
    phase: 2,
    mech: "Mirrors",
    prog_point_reached: "newphase",
    cause: "Ruv and Ella ice slide",
    players_responsible: JSON.stringify(["Ruv", "Ella"]),
    log_link: "",
    clip_link:
      "https://www.twitch.tv/xelahart/clip/ConsiderateChillyOctopusKappaWealth-jKRtlc15l-QiCRMh",
    notes:
      "Ruv gaze; I just realized I instinctively press W when I do swiftcast → res",
  },
];
