export default [
  {
    session_id: 1,
    pull_num_today: 1,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Laveera chains",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 2,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chro internet",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 3,
    phase: 1,
    mech: "Orbs & Portals",
    prog_point_reached: "old",
    cause: "Anivia and Char hit by orbs",
    players_responsible: "Anivia,Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 4,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chro banished to the nether realm",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 5,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Mystery tower explosion",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 6,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Anivia and Ella too slow for chain swap",
    players_responsible: "Anivia,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 7,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Chro's chain didn't swap",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 8,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Ruv not topped for raidwide",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 9,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chaos and suicide pacts",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 10,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Ruv not topped (Succor outranged)",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 11,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Everyone died to chains???",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 12,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Saki and Anivia chains",
    players_responsible: "Anivia,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 13,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Laveera late to soak",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 14,
    phase: 4,
    mech: "Chains",
    prog_point_reached: "target",
    cause: "Char damage down, Char + Chro accidental chain swap",
    players_responsible: "Char,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 15,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Dive chain swaps",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 16,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Ruv cleaved",
    players_responsible: "Ruvien",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 17,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Char impacted",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 18,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "NAUSEA HEARTBURN INDIGESTION UPSET STOMACH DIARRHEA",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 19,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Saki slow-motion suicide",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 20,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Ella missed heals",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 21,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Saki",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 22,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "Saki nakedlance",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 23,
    phase: 2,
    mech: "Sanctity of the Ward",
    prog_point_reached: "old",
    cause: "Cursed rock sounds",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 24,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Char baited geirskogul through stack",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 25,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Char 0.1 sec too late for chain swap",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 26,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Scuffed opener",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 27,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Ella ran into a 2",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 28,
    phase: 4,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "Ella and Laveera had weakness from Nid tank tether",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 29,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Enum chaos",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 1,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Chains",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 2,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "old",
    cause: "Ella not topped; enrage",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 3,
    phase: 1,
    mech: "Unknown",
    prog_point_reached: "old",
    cause: "Ella and Char chasing each other",
    players_responsible: "Ella,Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 4,
    phase: 3,
    mech: "Unknown",
    prog_point_reached: "cleanup",
    cause: "Laveera missing from stack, and Chro missed reprisal",
    players_responsible: "Laveera,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 5,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella too slow on strength",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 6,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Anivia ran into a wall",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 7,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Sanctity, 5/3 Anivia died and then Ruvien and Ella died too",
    players_responsible: "Anivia,Ruvien,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 8,
    phase: 3,
    mech: "Enum",
    prog_point_reached: "cleanup",
    cause: "Saki missed tank tether",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 9,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella gave Chro a hug on strength",
    players_responsible: "Ella,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 10,
    phase: 2,
    mech: "Unknown",
    prog_point_reached: "old",
    cause: "TANK HONOR HAS BEEN BESMIRCHED",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 11,
    phase: 3,
    mech: "Enum",
    prog_point_reached: "cleanup",
    cause: "Laveera wrong spot",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 12,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ruv hit on strength",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 13,
    phase: 4,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "0.1% enrage",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 14,
    phase: 4,
    mech: "Shockwaves",
    prog_point_reached: "target",
    cause: "Not enough mits/heals to keep party alive",
    players_responsible: "Ella,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 15,
    phase: 4,
    mech: "Shockwaves",
    prog_point_reached: "target",
    cause: "Mits/heals again",
    players_responsible: "Ella,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 16,
    phase: 3,
    mech: "Unknown",
    prog_point_reached: "cleanup",
    cause: "Saki’s controller unplugged and Ella’s deployment failed",
    players_responsible: "Saki,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 17,
    phase: 1,
    mech: "Unknown",
    prog_point_reached: "old",
    cause: "Missed heals?",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 18,
    phase: 1,
    mech: "Orbs & Portals",
    prog_point_reached: "old",
    cause: "Laveera and Saki died",
    players_responsible: "Laveera,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 19,
    phase: 1,
    mech: "Chains",
    prog_point_reached: "old",
    cause: "No mitigation on chains",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 20,
    phase: 4,
    mech: "Chains",
    prog_point_reached: "target",
    cause: "Char/Tori chain didn’t swap",
    players_responsible: "Char,Tori",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 21,
    phase: 2,
    mech: "Unknown",
    prog_point_reached: "old",
    cause: "SAKI is confused! It hurt itself in its confusion!",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 22,
    phase: 4,
    mech: "Shockwaves",
    prog_point_reached: "target",
    cause: "Needed more heals before last shockwave",
    players_responsible: "Ella,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 23,
    phase: 2,
    mech: "Unknown",
    prog_point_reached: "old",
    cause: "Saki got DD and then tank swap shenanigans",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 24,
    phase: 3,
    mech: "Enrage",
    prog_point_reached: "cleanup",
    cause: "Chro died to tankbuster",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 25,
    phase: 4,
    mech: "Unknown",
    prog_point_reached: "target",
    cause: "Ella died to damage, recovery struggle",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 26,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Sanctity meteor swap",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 27,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "cleanup",
    cause: "Saki misplaced 2 tower and ensuing geirskogul chaos",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 28,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella hit on Strength",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 29,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "newphase",
    cause: "First time seeing phase 5! Need shields/mits before WotH",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 30,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Chro and Ruv hit on Strength",
    players_responsible: "Chro,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 31,
    phase: 4,
    mech: "Unknown",
    prog_point_reached: "target",
    cause: "Char DCed, mega sad",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
];
