export default [
  {
    session_id: 1,
    pull_num_today: 1,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Laveera chains",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 2,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chro internet",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 3,
    phase: 1,
    mech: "Orbs & Portals",
    prog_point_reached: "old",
    cause: "Anivia and Char hit by orbs",
    players_responsible: "Anivia,Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 4,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chro banished to the nether realm",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 5,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Mystery tower explosion",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 6,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Anivia and Ella too slow for chain swap",
    players_responsible: "Anivia,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 7,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Chro's chain didn't swap",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 8,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Ruv not topped for raidwide",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 9,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chaos and suicide pacts",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 10,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Ruv not topped (Succor outranged)",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 11,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Everyone died to chains???",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 12,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Saki and Anivia chains",
    players_responsible: "Anivia,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 13,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Laveera late to soak",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 14,
    phase: 4,
    mech: "Chains",
    prog_point_reached: "target",
    cause: "Char damage down, Char + Chro accidental chain swap",
    players_responsible: "Char,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 15,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Dive chain swaps",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 16,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Ruv cleaved",
    players_responsible: "Ruvien",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 17,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Char impacted",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 18,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "NAUSEA HEARTBURN INDIGESTION UPSET STOMACH DIARRHEA",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 19,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Saki slow-motion suicide",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 20,
    phase: 2,
    mech: "Strength of the Ward",
    prog_point_reached: "old",
    cause: "Ella missed heals",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 21,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Saki",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 22,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "Saki nakedlance",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 23,
    phase: 2,
    mech: "Sanctity of the Ward",
    prog_point_reached: "old",
    cause: "Cursed rock sounds",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 24,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Char baited geirskogul through stack",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 25,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "target",
    cause: "Char 0.1 sec too late for chain swap",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 26,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Scuffed opener",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 27,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Ella ran into a 2",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 28,
    phase: 4,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "Ella and Laveera had weakness from Nid tank tether",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 1,
    pull_num_today: 29,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "cleanup",
    cause: "Enum chaos",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 1,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Chains",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 2,
    phase: 1,
    mech: "Enrage",
    prog_point_reached: "old",
    cause: "Ella not topped; enrage",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 3,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Ella and Char chasing each other",
    players_responsible: "Ella,Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 4,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "Laveera missing from stack, and Chro missed reprisal",
    players_responsible: "Laveera,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 5,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella too slow on strength",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 6,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Anivia ran into a wall",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 7,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Sanctity, 5/3 Anivia died and then Ruvien and Ella died too",
    players_responsible: "Anivia,Ruvien,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 8,
    phase: 3,
    mech: "Enum",
    prog_point_reached: "cleanup",
    cause: "Saki missed tank tether",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 9,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella gave Chro a hug on strength",
    players_responsible: "Ella,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 10,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "TANK HONOR HAS BEEN BESMIRCHED",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 11,
    phase: 3,
    mech: "Enum",
    prog_point_reached: "cleanup",
    cause: "Laveera wrong spot",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 12,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ruv hit on strength",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 13,
    phase: 4,
    mech: "Enrage",
    prog_point_reached: "target",
    cause: "0.1% enrage",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 14,
    phase: 4,
    mech: "Shockwaves",
    prog_point_reached: "target",
    cause: "Not enough mits/heals to keep party alive",
    players_responsible: "Ella,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 15,
    phase: 4,
    mech: "Shockwaves",
    prog_point_reached: "target",
    cause: "Mits/heals again",
    players_responsible: "Ella,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 16,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "Saki’s controller unplugged and Ella’s deployment failed",
    players_responsible: "Saki,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 17,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Missed heals?",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 18,
    phase: 1,
    mech: "Orbs & Portals",
    prog_point_reached: "old",
    cause: "Laveera and Saki died",
    players_responsible: "Laveera,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 19,
    phase: 1,
    mech: "Chains",
    prog_point_reached: "old",
    cause: "No mitigation on chains",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 20,
    phase: 4,
    mech: "Chains",
    prog_point_reached: "target",
    cause: "Char/Tori chain didn’t swap",
    players_responsible: "Char,Tori",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 21,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "SAKI is confused! It hurt itself in its confusion!",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 22,
    phase: 4,
    mech: "Shockwaves",
    prog_point_reached: "target",
    cause: "Needed more heals before last shockwave",
    players_responsible: "Ella,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 23,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Saki got DD and then tank swap shenanigans",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 24,
    phase: 3,
    mech: "Enrage",
    prog_point_reached: "cleanup",
    cause: "Chro died to tankbuster",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 25,
    phase: 4,
    mech: "Unknown Mech",
    prog_point_reached: "target",
    cause: "Ella died to damage, recovery struggle",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 26,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Sanctity meteor swap",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 27,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "cleanup",
    cause: "Saki misplaced 2 tower and ensuing geirskogul chaos",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 28,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella hit on Strength",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 29,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "newphase",
    cause: "First time seeing phase 5! Need shields/mits before WotH",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 30,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Chro and Ruv hit on Strength",
    players_responsible: "Chro,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 2,
    pull_num_today: 31,
    phase: 4,
    mech: "Unknown Mech",
    prog_point_reached: "target",
    cause: "Char DCed, mega sad",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 1,
    phase: 1,
    mech: "Orbs & Portals",
    prog_point_reached: "old",
    cause: "Char got orbed; Saki forgot rampart",
    players_responsible: "Char,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 2,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Char missed 2nd interrupt",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 3,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: " Ella died to damage; Saki-Ella chains broke late",
    players_responsible: "Ella,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 4,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Ruv-Chro chains",
    players_responsible: "Ruv,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 5,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "target",
    cause: "Wrath twisters",
    players_responsible: "",
    log_link: "",
    clip_link:
      "https://clips.twitch.tv/TemperedOnerousSwallowFloof-b37SmEjKpbPVotzK",
  },
  {
    session_id: 3,
    pull_num_today: 6,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Char too close to pass tether",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 7,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Rock sounds (Anivia had short side)",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 8,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Go home Laveera you’re drunk",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 9,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Saki half a sec too slow",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 10,
    phase: 4,
    mech: "Cones",
    prog_point_reached: "cleanup",
    cause: "Both tanks coned the party",
    players_responsible: "Saki,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 11,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Anivia sniped Saki with a geirskogul",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 12,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella stole strength tether",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 13,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chro forgot tank stance. Blame the tuna.",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 14,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Ella-Saki chains",
    players_responsible: "Ella,Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 15,
    phase: 4,
    mech: "Dives",
    prog_point_reached: "cleanup",
    cause: "Char too close on dives",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 16,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Tower too far north",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 17,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ruv amogus",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 18,
    phase: 4,
    mech: "Tethers",
    prog_point_reached: "cleanup",
    cause: "Anivia late tether pass",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 19,
    phase: 4,
    mech: "Healing",
    prog_point_reached: "cleanup",
    cause: "Party not topped",
    players_responsible: "Ella,Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 20,
    phase: 3,
    mech: "Enrage",
    prog_point_reached: "old",
    cause: "Ella DD and suicide",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 21,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Ella got hit and missed soak",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 22,
    phase: 4,
    mech: "Haurchefant",
    prog_point_reached: "cleanup",
    cause: "Haurchefant :((((((((",
    players_responsible: "Ella,Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 23,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Doesn’t count",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 3,
    pull_num_today: 24,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Ruv is tired. We all tired tbh",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 1,
    phase: 4,
    mech: "Unknown Mech",
    prog_point_reached: "cleanup",
    cause: "Party heals",
    players_responsible: "Ella,Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 2,
    phase: 3,
    mech: "Enrage",
    prog_point_reached: "old",
    cause: "Saki DD & suicide",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 3,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Char moved early",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 4,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Ruv DD & suicide",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 5,
    phase: 4,
    mech: "Enrage",
    prog_point_reached: "cleanup",
    cause: "0.1% enrage",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 6,
    phase: 4,
    mech: "Rewind",
    prog_point_reached: "cleanup",
    cause: "Haurchefant heals",
    players_responsible: "Anivia,Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 7,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella’s seraph missed Ruv",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 8,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella needs reverse rescue",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 9,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Chro swapped when it was DPS swap",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 10,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Anivia wrong button",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 11,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ruv: 'That’s blue, right?'",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 12,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Char, hesitation is defeat",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 13,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella, hesitation is defeat",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 14,
    phase: 3,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Weenie hut jr shields because Char died",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 15,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "target",
    cause: "No mits (and also twisters)",
    players_responsible: "",
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/1564237305",
  },
  {
    session_id: 4,
    pull_num_today: 16,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Interrupts",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 17,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Ella/Chro chains",
    players_responsible: "Ella,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 18,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Char/Tori chains",
    players_responsible: "Char,Tori",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 19,
    phase: 1,
    mech: "Playstation",
    prog_point_reached: "old",
    cause: "Char chains",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 20,
    phase: 1,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Saki went wrong way",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 21,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "target",
    cause: "Chro divebomb",
    players_responsible: "Chro",
    log_link: "",
    clip_link:
      "https://clips.twitch.tv/JollyMotionlessDuckSoBayed-0s5hZsyPtbZ7gfau",
  },
  {
    session_id: 4,
    pull_num_today: 22,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Saki late move",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 23,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella’s succor missed Ruv",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 24,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Laveera aneurysm strength",
    players_responsible: "Laveera",
    log_link: "",
    clip_link:
      "https://clips.twitch.tv/HeartlessCuriousMilkWow-LqkDkCvyi73WNxSK",
  },
  {
    session_id: 4,
    pull_num_today: 25,
    phase: 4,
    mech: "Rewind",
    prog_point_reached: "cleanup",
    cause: "Anivia hit by puddle",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 26,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Tori missed tower",
    players_responsible: "Tori",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 27,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Rock sounds, Saki’s finger slipped",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 28,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Ella too slow to get into tower",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 29,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Char tower placement",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 4,
    pull_num_today: 30,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Wyrmhole mystery",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 1,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Chro internet",
    players_responsible: "Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 2,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Char oopsie on sanctity",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 3,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ella stole tether",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 4,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Towers and the shukuchi struggle",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 5,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Anivia geirskogul’d",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 6,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Char geirskogul sextuple kill",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 7,
    phase: 3,
    mech: "Drachenlance",
    prog_point_reached: "old",
    cause: "Char drachenlanze",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 8,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Danger dorito hid the true danger",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 9,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Saki tank tether",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 10,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Ella hit by gnash & lash",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 11,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Xenoblade 3 is the best and also we’re all dead",
    players_responsible: "",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 12,
    phase: 2,
    mech: "Unknown Mech",
    prog_point_reached: "old",
    cause: "Saki internet",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 13,
    phase: 4,
    mech: "Tethers",
    prog_point_reached: "cleanup",
    cause: "Multiple swap problems",
    players_responsible: "",
    log_link: "",
    clip_link:
      "https://clips.twitch.tv/FilthyConfidentNuggetsTinyFace-NGNjZdFAq4TlNdmx",
  },
  {
    session_id: 5,
    pull_num_today: 14,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Char bad angle",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 15,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Anivia and Chro DD",
    players_responsible: "Anivia,Chro",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 16,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Char blue marker spot adjust dance",
    players_responsible: "Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 17,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Saki tower",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 18,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Anivia cones",
    players_responsible: "Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 19,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Laveera/Ruv swap",
    players_responsible: "Laveera,Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 20,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Rock sounds Ella",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 21,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Ella wrong spot",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 22,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "target",
    cause: "Saki blue marker placement + twisters",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "https://www.twitch.tv/videos/1566147859",
  },
  {
    session_id: 5,
    pull_num_today: 23,
    phase: 3,
    mech: "Enums",
    prog_point_reached: "old",
    cause: "Laveera tower",
    players_responsible: "Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 24,
    phase: 2,
    mech: "Strength",
    prog_point_reached: "old",
    cause: "Ruv cone",
    players_responsible: "Ruv",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 25,
    phase: 5,
    mech: "Wrath",
    prog_point_reached: "target",
    cause: "Ella/Laveera too close → caused liquid heaven mayhem",
    players_responsible: "Ella,Laveera",
    log_link: "",
    clip_link:
      "https://clips.twitch.tv/PoliteDeliciousGaurTriHard-I0CoUFE8nfj8kgAL",
  },
  {
    session_id: 5,
    pull_num_today: 26,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Ella lag",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 27,
    phase: 4,
    mech: "Swaps",
    prog_point_reached: "cleanup",
    cause: "More swap problems (Saki/Laveera/Char/everyone)",
    players_responsible: "Saki,Laveera,Char",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 28,
    phase: 4,
    mech: "Rewind",
    prog_point_reached: "cleanup",
    cause:
      "Party mits/heals, Char and Ruv died to damage. Had only soil, heart wore off 2 sec before. ~75% HP when cone hit, overkill by 6k. Needs more succor.",
    players_responsible: "Char,Ruv",
    log_link: "https://www.fflogs.com/reports/gkd2AxQpKzhTtnjr/#fight=30",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 29,
    phase: 3,
    mech: "Wyrmhole",
    prog_point_reached: "old",
    cause: "Saki soaked 2 and 3",
    players_responsible: "Saki",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 30,
    phase: 2,
    mech: "Sanctity",
    prog_point_reached: "old",
    cause: "Ella got iced",
    players_responsible: "Ella",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 31,
    phase: 4,
    mech: "Orbs",
    prog_point_reached: "cleanup",
    cause: "Char/Laveera popped orb out of sync",
    players_responsible: "Char,Laveera",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 32,
    phase: 4,
    mech: "Rewind",
    prog_point_reached: "cleanup",
    cause: "Haurchefant :(",
    players_responsible: "Ella,Anivia",
    log_link: "",
    clip_link: "",
  },
  {
    session_id: 5,
    pull_num_today: 33,
    phase: 3,
    mech: "Enrage",
    prog_point_reached: "old",
    cause:
      "Ruv died to Ultimate End damage. Had addle, feint, reprisal, heart, galvanize, and soil. Overkill by 2722",
    players_responsible: "",
    log_link:
      "https://www.fflogs.com/reports/gkd2AxQpKzhTtnjr/#fight=35&type=deaths&source=8&ability=25534&death=1",
    clip_link: "",
  },
];
