export default [
  {
    date: "2022-08-04",
    prog_phase: 4,
    prog_mech: "Dives",
    fflogs_link: "",
    twitch_link: "",
    roster: JSON.stringify([
      "Chro",
      "Tori",
      "Ruvien",
      "Ella",
      "Saki",
      "Anivia",
      "Char",
      "Laveera",
    ]),
  },
  {
    date: "2022-08-09",
    prog_phase: 4,
    prog_mech: "Rewind",
    fflogs_link: "",
    twitch_link: "",
    roster: JSON.stringify([
      "Chro",
      "Tori",
      "Ruvien",
      "Ella",
      "Saki",
      "Anivia",
      "Char",
      "Laveera",
    ]),
  },
  {
    date: "2022-08-11",
    prog_phase: 4,
    prog_mech: "Rewind",
    fflogs_link: "",
    twitch_link: "",
    roster: JSON.stringify([
      "Chro",
      "Tori",
      "Ruvien",
      "Ella",
      "Saki",
      "Anivia",
      "Char",
      "Laveera",
    ]),
  },
  {
    date: "2022-08-16",
    prog_phase: 5,
    prog_mech: "Wrath",
    fflogs_link: "",
    twitch_link: "",
    roster: JSON.stringify([
      "Chro",
      "Tori",
      "Ruvien",
      "Ella",
      "Saki",
      "Anivia",
      "Char",
      "Laveera",
    ]),
  },
  {
    date: "2022-08-18",
    prog_phase: 5,
    prog_mech: "Wrath",
    fflogs_link: "https://www.fflogs.com/reports/gkd2AxQpKzhTtnjr/",
    twitch_link: "",
    roster: JSON.stringify([
      "Chro",
      "Tori",
      "Ruvien",
      "Ella",
      "Saki",
      "Anivia",
      "Char",
      "Laveera",
    ]),
  },
];

// DSR Roster: "Chro,Tori,Ruvien,Ella,Quil,Anivia,Char,Laveera"
// FRU Roster: "Chro,Sophia,Ruvien,Ella,Quil,Hypatia,Char,Laveera"
