export const actionsArray = [
  {
    job: "AST",
    name: "Aspected Benefic",
    abbr: "AB",
    icon: "/actions/Aspected_Benefic.png",
    cd: 0,
  },
  {
    job: "AST",
    name: "Benefic II",
    abbr: "Ben2",
    icon: "/actions/Benefic_II.png",
    cd: 0,
  },
  {
    job: "AST",
    name: "Celestial Intersection",
    abbr: "Inter",
    icon: "/actions/Celestial_Intersection.png",
    cd: 30,
  },
  {
    job: "AST",
    name: "Celestial Opposition",
    abbr: "Oppo",
    icon: "/actions/Celestial_Opposition.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Collective Unconscious",
    abbr: "CU",
    icon: "/actions/Collective_Unconscious.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Earthly Star (Place)",
    abbr: "Star (Place)",
    icon: "/actions/Earthly_Star.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Essential Dignity",
    abbr: "ED",
    icon: "/actions/Essential_Dignity.png",
    cd: 40,
  },
  {
    job: "AST",
    name: "Exaltation",
    abbr: "Exalt",
    icon: "/actions/Exaltation.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Helios",
    abbr: "Hel",
    icon: "/actions/Helios.png",
    cd: 0,
  },
  {
    job: "AST",
    name: "Helios Conjunction",
    abbr: "HC",
    icon: "/actions/Helios_Conjunction.png",
    cd: 0,
  },
  {
    job: "AST",
    name: "Horoscope (Place)",
    abbr: "Horo (Place)",
    icon: "/actions/Horosocope_1.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Horoscope (Pop)",
    abbr: "Horo (Pop)",
    icon: "/actions/Horoscope_2.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Lady of Crowns",
    abbr: "Lady",
    icon: "/actions/Lady_of_Crowns.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "Macrocosmos",
    abbr: "Macro",
    icon: "/actions/Macrocosmos.png",
    cd: 180,
  },
  {
    job: "AST",
    name: "Microcosmos",
    abbr: "Micro",
    icon: "/actions/Microcosmos.png",
    cd: 180,
  },
  {
    job: "AST",
    name: "Neutral Sect",
    abbr: "NS",
    icon: "/actions/Neutral_Sect.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "Stellar Detonation",
    abbr: "Star (Pop)",
    icon: "/actions/Stellar_Detonation.png",
    cd: 60,
  },
  {
    job: "AST",
    name: "Sun Sign",
    abbr: "Sun",
    icon: "/actions/Sun_Sign.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "Synastry",
    abbr: "Syn",
    icon: "/actions/Synastry.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "The Arrow",
    abbr: "Arrow",
    icon: "/actions/The_Arrow.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "The Bole",
    abbr: "Bole",
    icon: "/actions/The_Bole.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "The Ewer",
    abbr: "Ewer",
    icon: "/actions/The_Ewer.png",
    cd: 120,
  },
  {
    job: "AST",
    name: "The Spire",
    abbr: "Spire",
    icon: "/actions/The_Spire.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Diagnosis",
    abbr: "Diag",
    icon: "/actions/Diagnosis.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Druochole",
    abbr: "Druo",
    icon: "/actions/Druochole.png",
    cd: 1,
  },
  {
    job: "SGE",
    name: "Eukrasian Diagnosis",
    abbr: "ED",
    icon: "/actions/Eukrasian_Diagnosis.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Eukrasian Prognosis II",
    abbr: "EP",
    icon: "/actions/Eukrasian_Prognosis_II.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Haima",
    abbr: "Haima",
    icon: "/actions/Haima.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Holos",
    abbr: "Holos",
    icon: "/actions/Holos.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Ixochole",
    abbr: "Ixo",
    icon: "/actions/Ixochole.png",
    cd: 30,
  },
  {
    job: "SGE",
    name: "Kerachole",
    abbr: "Kera",
    icon: "/actions/Kerachole.png",
    cd: 30,
  },
  {
    job: "SGE",
    name: "Krasis",
    abbr: "Krasis",
    icon: "/actions/Krasis.png",
    cd: 60,
  },
  {
    job: "SGE",
    name: "Panhaima",
    abbr: "Pan",
    icon: "/actions/Panhaima.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Pepsis",
    abbr: "Pepsis",
    icon: "/actions/Pepsis.png",
    cd: 30,
  },
  {
    job: "SGE",
    name: "Philosophia",
    abbr: "Phil",
    icon: "/actions/Philosophia.png",
    cd: 180,
  },
  {
    job: "SGE",
    name: "Physis II",
    abbr: "Phys",
    icon: "/actions/Physis_II.png",
    cd: 60,
  },
  {
    job: "SGE",
    name: "Pneuma",
    abbr: "Pneuma",
    icon: "/actions/Pneuma.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Prognosis",
    abbr: "Prog",
    icon: "/actions/Prognosis.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Soteria",
    abbr: "Soteria",
    icon: "/actions/Soteria.png",
    cd: 60,
  },
  {
    job: "SGE",
    name: "Taurochole",
    abbr: "Tauro",
    icon: "/actions/Taurochole.png",
    cd: 45,
  },
  {
    job: "SGE",
    name: "Zoe",
    abbr: "Z",
    icon: "/actions/Zoe.png",
    cd: 90,
  },
];
