export const actionsArray = [
  {
    job: "SGE",
    name: "Diagnosis",
    abbr: "Diag",
    icon: "/actions/Diagnosis.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Druochole",
    abbr: "Druo",
    icon: "/actions/Druochole.png",
    cd: 1,
  },
  {
    job: "SGE",
    name: "Eukrasian Diagnosis",
    abbr: "ED",
    icon: "/actions/Eukrasian_Diagnosis.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Eukrasian Prognosis II",
    abbr: "EP",
    icon: "/actions/Eukrasian_Prognosis_II.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Haima",
    abbr: "Haima",
    icon: "/actions/Haima.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Holos",
    abbr: "Holos",
    icon: "/actions/Holos.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Ixochole",
    abbr: "Ixo",
    icon: "/actions/Ixochole.png",
    cd: 30,
  },
  {
    job: "SGE",
    name: "Kerachole",
    abbr: "Kera",
    icon: "/actions/Kerachole.png",
    cd: 30,
  },
  {
    job: "SGE",
    name: "Krasis",
    abbr: "Krasis",
    icon: "/actions/Krasis.png",
    cd: 60,
  },
  {
    job: "SGE",
    name: "Panhaima",
    abbr: "Pan",
    icon: "/actions/Panhaima.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Pepsis",
    abbr: "Pepsis",
    icon: "/actions/Pepsis.png",
    cd: 30,
  },
  {
    job: "SGE",
    name: "Philosophia",
    abbr: "Phil",
    icon: "/actions/Philosophia.png",
    cd: 180,
  },
  {
    job: "SGE",
    name: "Physis II",
    abbr: "Phys",
    icon: "/actions/Physis_II.png",
    cd: 60,
  },
  {
    job: "SGE",
    name: "Pneuma",
    abbr: "Pneuma",
    icon: "/actions/Pneuma.png",
    cd: 120,
  },
  {
    job: "SGE",
    name: "Prognosis",
    abbr: "Prog",
    icon: "/actions/Prognosis.png",
    cd: 0,
  },
  {
    job: "SGE",
    name: "Soteria",
    abbr: "Soteria",
    icon: "/actions/Soteria.png",
    cd: 60,
  },
  {
    job: "SGE",
    name: "Taurochole",
    abbr: "Tauro",
    icon: "/actions/Taurochole.png",
    cd: 45,
  },
  {
    job: "SGE",
    name: "Zoe",
    abbr: "Z",
    icon: "/actions/Zoe.png",
    cd: 90,
  },
];
