const session1 = {
  sessionDate: "Friday August 4th",
  sessionNum: 1,
  fflogsLink: "",
  twitchLink: "",
  pulls: [
    {
      pullNumToday: 1,
      pullNumTotal: 1,
      duration: "",
      phase: 1,
      mech: "Playstation",
      wipeCause: "Laveera chains",
      playerNames: ["Laveera"],
      progPointReached: "old",
    },
    {
      pullNumToday: 2,
      pullNumTotal: 2,
      duration: "",
      phase: 1,
      mech: "Unknown",
      wipeCause: "Chro internet",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 3,
      pullNumTotal: 3,
      duration: "",
      phase: 1,
      mech: "Orbs & Portals",
      wipeCause: "Anivia and Char hit by orbs",
      playerNames: ["Anivia", "Char"],
      progPointReached: "old",
    },
    {
      pullNumToday: 4,
      pullNumTotal: 4,
      duration: "",
      phase: 2,
      mech: "Unknwon",
      wipeCause: "Chro banished to the nether realm",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 5,
      pullNumTotal: 5,
      duration: "",
      phase: 2,
      mech: "Strength of the Ward",
      wipeCause: "Mystery tower explosion",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 6,
      pullNumTotal: 6,
      duration: "",
      phase: 4,
      mech: "Dives",
      wipeCause: "Anivia and Ella too slow for chain swap",
      playerNames: ["Anivia", "Ella"],
      progPointReached: "target",
    },
    {
      pullNumToday: 7,
      pullNumTotal: 7,
      duration: "",
      phase: 4,
      mech: "Dives",
      wipeCause: "Chro's chain didn't swap",
      playerNames: ["Chro"],
      progPointReached: "target",
    },
    {
      pullNumToday: 8,
      pullNumTotal: 8,
      duration: "",
      phase: 1,
      mech: "Unknown",
      wipeCause: "Ruv not topped for raidwide",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 9,
      pullNumTotal: 9,
      duration: "",
      phase: 1,
      mech: "Unknown",
      wipeCause: "Chaos and suicide pacts",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 10,
      pullNumTotal: 10,
      duration: "",
      phase: 1,
      mech: "Unknown",
      wipeCause: "Ruv not topped (Succor outranged)",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 11,
      pullNumTotal: 11,
      duration: "",
      phase: 1,
      mech: "Playstation",
      wipeCause: "Everyone died to chains???",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 12,
      pullNumTotal: 12,
      duration: "",
      phase: 1,
      mech: "Playstation",
      wipeCause: "Saki and Anivia chains",
      playerNames: ["Anivia", "Saki"],
      progPointReached: "old",
    },
    {
      pullNumToday: 13,
      pullNumTotal: 13,
      duration: "",
      phase: 3,
      mech: "Enums",
      wipeCause: "Laveera late to soak",
      playerNames: ["Laveera"],
      progPointReached: "cleanup",
    },
    {
      pullNumToday: 14,
      pullNumTotal: 14,
      duration: "",
      phase: 4,
      mech: "Chains",
      wipeCause: "Char damage down, Char + Chro accidental chain swap",
      playerNames: ["Char", "Chro"],
      progPointReached: "target",
    },
    {
      pullNumToday: 15,
      pullNumTotal: 15,
      duration: "",
      phase: 4,
      mech: "Dives",
      wipeCause: "Dive chain swaps",
      playerNames: [],
      progPointReached: "target",
    },
    {
      pullNumToday: 16,
      pullNumTotal: 16,
      duration: "",
      phase: 2,
      mech: "Strength of the Ward",
      wipeCause: "Ruv cleaved",
      playerNames: ["Ruvien"],
      progPointReached: "old",
    },
    {
      pullNumToday: 17,
      pullNumTotal: 17,
      duration: "",
      phase: 2,
      mech: "Strength of the Ward",
      wipeCause: "Char impacted",
      playerNames: ["Char"],
      progPointReached: "old",
    },
    {
      pullNumToday: 18,
      pullNumTotal: 18,
      duration: "",
      phase: 3,
      mech: "Unknown",
      wipeCause: "NAUSEA HEARTBURN INDIGESTION UPSET STOMACH DIARRHEA",
      playerNames: [],
      progPointReached: "cleanup",
    },
    {
      pullNumToday: 19,
      pullNumTotal: 19,
      duration: "",
      phase: 2,
      mech: "Unknown",
      wipeCause: "Saki slow-motion suicide",
      playerNames: ["Saki"],
      progPointReached: "old",
    },
    {
      pullNumToday: 20,
      pullNumTotal: 20,
      duration: "",
      phase: 2,
      mech: "Strength of the Ward",
      wipeCause: "Ella missed heals",
      playerNames: ["Ella"],
      progPointReached: "old",
    },
    {
      pullNumToday: 21,
      pullNumTotal: 21,
      duration: "",
      phase: 4,
      mech: "Dives",
      wipeCause: "Saki",
      playerNames: ["Saki"],
      progPointReached: "target",
    },
    {
      pullNumToday: 22,
      pullNumTotal: 22,
      duration: "",
      phase: 3,
      mech: "Unknown",
      wipeCause: "Saki nakedlance",
      playerNames: ["Saki"],
      progPointReached: "cleanup",
    },
    {
      pullNumToday: 23,
      pullNumTotal: 23,
      duration: "",
      phase: 2,
      mech: "Sanctity of the Ward",
      wipeCause: "Cursed rock sounds",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 24,
      pullNumTotal: 24,
      duration: "",
      phase: 3,
      mech: "Enums",
      wipeCause: "Char baited geirskogul through stack",
      playerNames: ["Char"],
      progPointReached: "cleanup",
    },
    {
      pullNumToday: 25,
      pullNumTotal: 25,
      duration: "",
      phase: 4,
      mech: "Dives",
      wipeCause: "Char 0.1 sec too late for chain swap",
      playerNames: ["Char"],
      progPointReached: "target",
    },
    {
      pullNumToday: 26,
      pullNumTotal: 26,
      duration: "",
      phase: 2,
      mech: "Unknown",
      wipeCause: "Scuffed opener",
      playerNames: [],
      progPointReached: "old",
    },
    {
      pullNumToday: 27,
      pullNumTotal: 27,
      duration: "",
      phase: 3,
      mech: "Enums",
      wipeCause: "Ella ran into a 2",
      playerNames: ["Ella"],
      progPointReached: "cleanup",
    },
    {
      pullNumToday: 28,
      pullNumTotal: 28,
      duration: "",
      phase: 4,
      mech: "Enrage",
      wipeCause: "Ella and Laveera had weakness from Nid tank tether",
      playerNames: [],
      progPointReached: "target",
    },
    {
      pullNumToday: 29,
      pullNumTotal: 29,
      duration: "",
      phase: 3,
      mech: "Enums",
      wipeCause: "Enum chaos",
      playerNames: [],
      progPointReached: "cleanup",
    },
  ],
};
