export const phases = [
  {
    phaseNum: 1,
    phaseName: "Fatebreaker",
    mechs: ["P1 Opener", "Utopian Sky", "Fall of Faith", "Towers"],
  },
  {
    phaseNum: 2,
    phaseName: "Shiva",
    mechs: [
      "P2 Opener",
      "Diamond Dust",
      "Mirror, Mirror",
      "Light Rampant",
      "P2 Enrage",
      "Intermission",
    ],
  },
  { phaseNum: 3, phaseName: "Gaia" },
  { phaseNum: 4, phaseName: "Roommates" },
  { phaseNum: 5, phaseName: "Pandora" },
];

export const timeline = [
  {
    phase: 1,
    boss: "Fatebreaker",
    startTime: "0:00",
    endTime: "2:37 (hard enrage 2:46)",
    mechs: [
      {
        mechName: "Opener",
        startTime: "0:00",
        endTime: "0:34",
        submechs: [
          {
            time: "0:14",
            mech: "Cyclonic Break",
            nickname: "proteans",
            maxDmg: 97,
          },
          {
            time: "0:16",
            mech: "Sinsmoke/Sinsmite",
            nickname: "partner stack/spread",
            maxDmg: 146,
          },
          {
            time: "0:24",
            mech: "Powder Mark Trail",
            nickname: "single TB",
            maxDmg: 0,
            tankbuster: true,
          },
        ],
      },
      {
        mechName: "Utopian Sky",
        startTime: "0:34",
        endTime: "1:20",
        untargetable: true,
        submechs: [
          {
            time: "0:40",
            mech: "Burn Mark",
            nickname: "double TB",
            maxDmg: 0,
            tankbuster: true,
          },
          {
            time: "0:49",
            mech: "Sinbound Fire/Thunder III",
            nickname: "light party stack/spread",
            maxDmg: 0,
          },
          {
            time: "0:56",
            mech: "Cyclonic Break",
            nickname: "proteans",
            maxDmg: 0,
          },
          {
            time: "0:58",
            mech: "Sinsmoke/Sinsmite",
            nickname: "partner stack/spread",
            maxDmg: 0,
          },
          {
            time: "1:18",
            mech: "Sinsmoke",
            nickname: "tether stacks",
            maxDmg: 0,
          },
        ],
      },
      {
        mechName: "Fall of Faith",
        startTime: "1:20",
        endTime: "2:05",
        submechs: [
          {
            time: "1:26",
            mech: "Burnished Glory",
            nickname: "DoT",
            maxDmg: 0,
          },
          {
            time: "1:41",
            mech: "Fall of Faith",
            nickname: "castbar ends",
            maxDmg: 0,
          },
          {
            time: "1:45",
            mech: "Sinblaze/Sinsmite/Bow Shock",
            nickname: "stack/cones",
            maxDmg: 0,
            repeatsAt: ["1:48, 1:51, 1:54"],
          },
          {
            time: "2:01",
            mech: "Burnished Glory",
            nickname: "DoT",
            maxDmg: 0,
          },
        ],
      },
      {
        mechName: "Towers",
        startTime: "2:05",
        endTime: "2:37",
        submechs: [
          {
            time: "2:10",
            mech: "Powder Mark Trail",
            nickname: "single TB",
            maxDmg: 0,
            tankbuster: true,
          },
          { time: "2:25", mech: "Explosion", nickname: "towers", maxDmg: 0 },
          {
            time: "2:26",
            mech: "Burn Mark",
            nickname: "double TB",
            maxDmg: 0,
            tankbuster: true,
          },
        ],
      },
    ],
  },
];

export const timeline2 = [
  {
    name: "Cyclonic Break",
    nickname: "proteans",
    time: "0:14",
    phase: 1,
    subphase: "P1 Opener",
  },
  {
    name: "Sinsmoke/Sinsmite",
    nickname: "partner stack/spread",
    time: "0:16",
    phase: 1,
    subphase: "P1 Opener",
  },
  {
    name: "Powder Mark Trail",
    nickname: "single TB",
    time: "0:24",
    phase: 1,
    subphase: "P1 Opener",
  },
  {
    name: "Burn Mark",
    nickname: "double TB",
    time: "0:40",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Sinbound Fire/Thunder III",
    nickname: "stack/spread",
    time: "0:49",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Cyclonic Break",
    nickname: "proteans",
    time: "0:56",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Sinsmoke/Sinsmite",
    nickname: "stack/spread",
    time: "0:58",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Sinsmoke",
    nickname: "tether stacks",
    time: "1:18",
    phase: 1,
    subphase: "Fall of Faith",
  },
  {
    name: "Burnished Glory",
    nickname: "DoT",
    time: "1:26",
    ticksUntil: "1:41",
    phase: 1,
    subphase: "Fall of Faith",
  },
  {
    name: "Fall of Faith",
    nickname: "tethers",
    time: "1:45",
    additionalHitsAt: ["1:48", "1:51", "1:54"],
    phase: 1,
    subphase: "Fall of Faith",
  },
  {
    name: "Burnished Glory",
    nickname: "DoT",
    time: "2:01",
    ticksUntil: "2:16",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Powder Mark Trail",
    nickname: "single TB",
    time: "2:09",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Explosion",
    nickname: "towers",
    time: "2:25",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Burn Mark",
    nickname: "double TB",
    time: "2:26",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Quadruple Slap",
    nickname: "TB",
    time: "2:51",
    additionalHitsAt: ["2:55"],
    phase: 2,
    subphase: "P2 Opener",
  },
  {
    name: "Diamond Dust",
    nickname: "castbar",
    time: "3:11",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "The House of Light",
    nickname: "cones",
    time: "3:21",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Frigid Stone",
    nickname: "stars",
    time: "3:23",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Heavenly Strike",
    nickname: "KB",
    time: "3:27",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Sinbound Holy",
    nickname: "stack puddles",
    time: "3:31",
    additionalHitsAt: ["3:33", "3:34", "3:36"],
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Hallowed Ray",
    nickname: "line stack",
    time: "3:59",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "The House of Light",
    nickname: "proteans",
    time: "4:23",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "The House of Light",
    nickname: "proteans",
    time: "4:33",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "Banish III",
    nickname: "stack/spread",
    time: "4:39",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "Light Rampant",
    nickname: "castbar",
    time: "4:48",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Luminous Hammer",
    nickname: "puddles",
    time: "4:56",
    additionalHitsAt: ["4:58", "4:59", "5:01", "5:02"],
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Bright Hunger",
    nickname: "towers",
    time: "4:59",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Powerful Light",
    nickname: "stacks",
    time: "5:05",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Bright Hunger",
    nickname: "2s tower",
    time: "5:14",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Banish III",
    nickname: "stack/spread",
    time: "5:17",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "The House of Light",
    nickname: "proteans",
    time: "5:26",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Absolute Zero",
    nickname: "phase ender",
    time: "5:45",
    phase: 2,
    subphase: "P2 Enrage",
  },
  {
    name: "Junction",
    nickname: "transition raidwide",
    time: "7:03",
    phase: 2,
    subphase: "Intermission",
  },
  {
    name: "Hell's Judgment",
    nickname: "1 HP",
    time: "7:21",
    phase: 3,
    subphase: "P3 Opener",
  },
  {
    name: "Ultimate Relativity",
    nickname: "castbar",
    time: "7:36",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Dark Fire III/Unholy Darkness",
    nickname: "10s fires/stack",
    time: "7:47",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Sinbound Meltdown",
    nickname: "first lasers/rewinds",
    time: "7:53",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Dark Fire III/Unholy Darkness",
    nickname: "20s fires/stack + ice donut",
    time: "7:57",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Sinbound Meltdown",
    nickname: "second lasers/rewinds",
    time: "8:03",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Dark Fire III/Unholy Darkness",
    nickname: "30s fires/stack",
    time: "8:07",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Sinbound Meltdown",
    nickname: "third lasers",
    time: "8:14",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Dark Eruption/Dark Water III",
    nickname: "rewinds resolve",
    time: "8:19",
    phase: 3,
    subphase: "Ultimate Relativity",
  },
  {
    name: "Shell Crusher",
    nickname: "stack",
    time: "8:24",
    phase: 3,
    subphase: "P3 In-Between",
  },
  {
    name: "Shockwave Pulsar",
    nickname: "raidwide",
    time: "8:32",
    phase: 3,
    subphase: "P3 In-Between",
  },
  {
    name: "Black Halo",
    nickname: "TB",
    time: "8:40",
    phase: 3,
    subphase: "P3 In-Between",
  },
  {
    name: "Dark Water III",
    nickname: "1st stack",
    time: "9:08",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Spirit Taker",
    nickname: "spread",
    time: "9:10",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Dark Eruption",
    nickname: "spread",
    time: "9:21",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Dark Water III",
    nickname: "2nd stack",
    time: "9:27",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Darkest Dance",
    nickname: "TB",
    time: "9:29",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Darkest Dance",
    nickname: "KB",
    time: "9:32",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Dark Water III",
    nickname: "3rd stacks",
    time: "9:36",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Shockwave Pulsar",
    nickname: "RW",
    time: "9:42",
    phase: 3,
    subphase: "Apocalypse",
  },
  {
    name: "Memory's End",
    nickname: "phase ender",
    time: "9:55",
    phase: 3,
    subphase: "P3 Enrage",
  },
  {
    name: "Edge of Oblivion",
    nickname: "crystal pulse",
    time: "10:29",
    phase: 4,
    subphase: "P4 Opener",
  },
  {
    name: "Darklit Dragonsong",
    nickname: "castbar",
    time: "10:38",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Bright Hunger",
    nickname: "towers",
    time: "10:49",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "The Path of Light",
    nickname: "cones",
    time: "10:50",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Spirit Taker",
    nickname: "spread",
    time: "10:53",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Dark Water III",
    nickname: "stack",
    time: "10:57",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Somber Dance",
    nickname: "TB on furthest",
    time: "11:01",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Somber Dance",
    nickname: "TB on nearest",
    time: "11:04",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Edge of Oblivion",
    nickname: "crystal pulse",
    time: "11:07",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Akh Morn",
    nickname: "stack",
    time: "11:15",
    additionalHitsAt: ["11:16, 11:17, 11:18"],
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Morn Afah",
    nickname: "HP check",
    time: "11:25",
    phase: 4,
    subphase: "Darklit Dragonsong",
  },
  {
    name: "Crystallize Time",
    nickname: "castbar",
    time: "11:40",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Edge of Oblivion",
    nickname: "crystal pulse",
    time: "11:46",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Dark Water III",
    nickname: "stack",
    time: "11:52",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Longing of the Lost",
    nickname: "red ice dragon head",
    time: "11:54",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Dark Aero III/Dark Eruption",
    nickname: "KB/purple debuff",
    time: "11:54",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Unholy Darkness",
    nickname: "stack",
    time: "11:57",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Longing of the Lost",
    nickname: "red aero dragon head",
    time: "11:58",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Quietus",
    nickname: "RW debuffs",
    time: "12:11",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Spirit Taker",
    nickname: "spread",
    time: "12:17",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Hallowed Wings",
    nickname: "KB wings",
    time: "12:23",
    additionalHitsAt: ["12:27"],
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Akh Morn",
    nickname: "stack",
    time: "12:38",
    additionalHitsAt: ["12:39, 12:40, 12:41"],
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Edge of Oblivion",
    nickname: "crystal pulse",
    time: "12:45",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Morn Afah",
    nickname: "HP check",
    time: "12:48",
    phase: 4,
    subphase: "Crystallize Time",
  },
  {
    name: "Memory's End & Absolute Zero",
    nickname: "P4 enrage",
    time: "13:02",
    phase: 4,
    subphase: "P4 Enrage",
  },
  {
    name: "Fulgent Blade",
    nickname: "exa waves",
    time: "14:21",
    phase: 5,
    subphase: "Exas",
  },
  {
    name: "Akh Morn",
    nickname: "light party stacks",
    time: "14:48",
    phase: 5,
    subphase: "Exas",
  },
  {
    name: "Wings Dark and Light + Explosion",
    nickname: "TBs + healer towers",
    time: "15:07",
    phase: 5,
    subphase: "Towers",
  },
  {
    name: "Wings Dark and Light + Explosion",
    nickname: "TBs + 1st DPS towers",
    time: "15:10",
    phase: 5,
    subphase: "Towers",
  },
  {
    name: "Explosion",
    nickname: "2nd DPS towers",
    time: "15:14",
    phase: 5,
    subphase: "Towers",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (tanks in front)",
    time: "15:28",
    phase: 5,
    subphase: "Lines",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (melees in front)",
    time: "15:33",
    phase: 5,
    subphase: "Lines",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (ranged in front)",
    time: "15:38",
    phase: 5,
    subphase: "Lines",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (healers in front)",
    time: "15:43",
    phase: 5,
    subphase: "Lines",
  },
  {
    name: "Pandora's Box",
    nickname: "big raidwide (tank LB3)",
    time: "16:02",
    phase: 5,
    subphase: "",
  },
  {
    name: "Fulgent Blade",
    nickname: "exa waves",
    time: "16:14",
    phase: 5,
    subphase: "2nd Exas",
  },
  {
    name: "Akh Morn",
    nickname: "light party stacks",
    time: "16:41",
    phase: 5,
    subphase: "2nd Exas",
  },
  {
    name: "Wings Dark and Light + Explosion",
    nickname: "TBs + healer towers",
    time: "17:05",
    phase: 5,
    subphase: "2nd Towers",
  },
  {
    name: "Wings Dark and Light + Explosion",
    nickname: "TBs + 1st DPS towers",
    time: "17:09",
    phase: 5,
    subphase: "2nd Towers",
  },
  {
    name: "Explosion",
    nickname: "2nd DPS towers",
    time: "17:11",
    phase: 5,
    subphase: "2nd Towers",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (tanks in front)",
    time: "17:20",
    phase: 5,
    subphase: "2nd Lines",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (melees in front)",
    time: "17:25",
    phase: 5,
    subphase: "2nd Lines",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (ranged in front)",
    time: "17:30",
    phase: 5,
    subphase: "2nd Lines",
  },
  {
    name: "Cruel Path of Light/Darkness",
    nickname: "lines (healers in front)",
    time: "17:35",
    phase: 5,
    subphase: "2nd Lines",
  },
  {
    name: "Fulgent Blade",
    nickname: "exa waves",
    time: "17:45",
    phase: 5,
    subphase: "3rd Exas",
  },
  {
    name: "Akh Morn",
    nickname: "light party stacks",
    time: "18:12",
    phase: 5,
    subphase: "3rd Exas",
  },
  {
    name: "Paradise Lost",
    nickname: "P5 enrage",
    time: "18:33",
    phase: 5,
    subphase: "P5 Enrage",
  },
];

export const dpsTimeline = [
  {
    name: "Start",
    time: "0:00",
    phase: 1,
    uptime: true,
  },
  {
    name: "P1 Ideal Kill Time",
    time: "2:37",
    phase: 1,
    uptime: false,
  },

  {
    name: "P2 Start",
    time: "2:41",
    phase: 2,
    uptime: true,
  },
  {
    name: "Diamond Dust",
    time: "3:16",
    phase: 2,
    uptime: false,
  },
  {
    name: "Mirrors (Targetable)",
    time: "3:53",
    phase: 2,
    uptime: true,
  },
  {
    name: "Light Rampant",
    time: "4:53",
    phase: 2,
    uptime: false,
  },
  {
    name: "P2 End",
    time: "5:22",
    phase: 2,
    uptime: true,
  },
  {
    name: "P2 Transition",
    time: "5:46",
    phase: 2,
    uptime: false,
  },
  {
    name: "Intermission Start",
    time: "6:08",
    phase: 2,
    uptime: true,
  },
  {
    name: "Gaia Smash",
    time: "6:51",
    phase: 2,
    uptime: false,
  },

  {
    name: "P3 Start",
    time: "7:19",
    phase: 3,
    uptime: true,
  },
  {
    name: "P3 End",
    time: "10:00",
    phase: 3,
    uptime: false,
  },

  {
    name: "P4 Start (Ryne Only)",
    time: "10:06",
    phase: 4,
    uptime: true,
  },
  {
    name: "Gaia Targetable",
    time: "10:31",
    phase: 4,
    uptime: true,
  },
  {
    name: "Crystalize Time",
    time: "11:45",
    phase: 4,
    uptime: false,
  },
  {
    name: "P4 End",
    time: "12:34",
    phase: 4,
    uptime: true,
  },
  {
    name: "P4 Ideal Kill Time",
    time: "12:53",
    phase: 4,
    uptime: false,
  },

  {
    name: "P4 End",
    time: "12:34",
    phase: 4,
    uptime: true,
  },
  {
    name: "P4 Ideal Kill Time",
    time: "12:53",
    phase: 4,
    uptime: false,
  },

  {
    name: "Cutscene",
    time: "13:03",
    phase: 5,
    uptime: false,
  },
  {
    name: "P5 Start",
    time: "14:09",
    phase: 5,
    uptime: true,
  },
  {
    name: "P5 Enrage",
    time: "18:33",
    phase: 5,
    uptime: false,
  },
];
