export const phases = [
  {
    phaseNum: 1,
    phaseName: "Fatebreaker",
    mechs: ["P1 Opener", "Utopian Sky", "Fall of Faith", "Towers"],
  },
  {
    phaseNum: 2,
    phaseName: "Shiva",
    mechs: [
      "P2 Opener",
      "Diamond Dust",
      "Mirror, Mirror",
      "Light Rampant",
      "P2 Enrage",
      "Intermission",
    ],
  },
];

export const timeline = [
  {
    phase: 1,
    boss: "Fatebreaker",
    startTime: "0:00",
    endTime: "2:37 (hard enrage 2:46)",
    mechs: [
      {
        mechName: "Opener",
        startTime: "0:00",
        endTime: "0:34",
        submechs: [
          {
            time: "0:14",
            mech: "Cyclonic Break",
            nickname: "proteans",
            maxDmg: 97,
          },
          {
            time: "0:16",
            mech: "Sinsmoke/Sinsmite",
            nickname: "partner stack/spread",
            maxDmg: 146,
          },
          {
            time: "0:24",
            mech: "Powder Mark Trail",
            nickname: "single TB",
            maxDmg: 0,
            tankbuster: true,
          },
        ],
      },
      {
        mechName: "Utopian Sky",
        startTime: "0:34",
        endTime: "1:20",
        untargetable: true,
        submechs: [
          {
            time: "0:40",
            mech: "Burn Mark",
            nickname: "double TB",
            maxDmg: 0,
            tankbuster: true,
          },
          {
            time: "0:49",
            mech: "Sinbound Fire/Thunder III",
            nickname: "light party stack/spread",
            maxDmg: 0,
          },
          {
            time: "0:56",
            mech: "Cyclonic Break",
            nickname: "proteans",
            maxDmg: 0,
          },
          {
            time: "0:58",
            mech: "Sinsmoke/Sinsmite",
            nickname: "partner stack/spread",
            maxDmg: 0,
          },
          {
            time: "1:18",
            mech: "Sinsmoke",
            nickname: "tether stacks",
            maxDmg: 0,
          },
        ],
      },
      {
        mechName: "Fall of Faith",
        startTime: "1:20",
        endTime: "2:05",
        submechs: [
          {
            time: "1:26",
            mech: "Burnished Glory",
            nickname: "DoT",
            maxDmg: 0,
          },
          {
            time: "1:41",
            mech: "Fall of Faith",
            nickname: "castbar ends",
            maxDmg: 0,
          },
          {
            time: "1:45",
            mech: "Sinblaze/Sinsmite/Bow Shock",
            nickname: "stack/cones",
            maxDmg: 0,
            repeatsAt: ["1:48, 1:51, 1:54"],
          },
          {
            time: "2:01",
            mech: "Burnished Glory",
            nickname: "DoT",
            maxDmg: 0,
          },
        ],
      },
      {
        mechName: "Towers",
        startTime: "2:05",
        endTime: "2:37",
        submechs: [
          {
            time: "2:10",
            mech: "Powder Mark Trail",
            nickname: "single TB",
            maxDmg: 0,
            tankbuster: true,
          },
          { time: "2:25", mech: "Explosion", nickname: "towers", maxDmg: 0 },
          {
            time: "2:26",
            mech: "Burn Mark",
            nickname: "double TB",
            maxDmg: 0,
            tankbuster: true,
          },
        ],
      },
    ],
  },
];

export const timeline2 = [
  {
    name: "Cyclonic Break",
    nickname: "proteans",
    time: "0:14",
    phase: 1,
    subphase: "P1 Opener",
  },
  {
    name: "Sinsmoke/Sinsmite",
    nickname: "partner stack/spread",
    time: "0:16",
    phase: 1,
    subphase: "P1 Opener",
  },
  {
    name: "Powder Mark Trail",
    nickname: "single TB",
    time: "0:24",
    phase: 1,
    subphase: "P1 Opener",
  },
  {
    name: "Burn Mark",
    nickname: "double TB",
    time: "0:40",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Sinbound Fire/Thunder III",
    nickname: "stack/spread",
    time: "0:49",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Cyclonic Break",
    nickname: "proteans",
    time: "0:56",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Sinsmoke/Sinsmite",
    nickname: "stack/spread",
    time: "0:58",
    phase: 1,
    subphase: "Utopian Sky",
  },
  {
    name: "Sinsmoke",
    nickname: "tether stacks",
    time: "1:18",
    phase: 1,
    subphase: "Fall of Faith",
  },
  {
    name: "Burnished Glory",
    nickname: "DoT",
    time: "1:26",
    ticksUntil: "1:41",
    phase: 1,
    subphase: "Fall of Faith",
  },
  {
    name: "Fall of Faith",
    nickname: "tethers",
    time: "1:45",
    additionalHitsAt: ["1:48", "1:51", "1:54"],
    phase: 1,
    subphase: "Fall of Faith",
  },
  {
    name: "Burnished Glory",
    nickname: "DoT",
    time: "2:01",
    ticksUntil: "2:16",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Powder Mark Trail",
    nickname: "single TB",
    time: "2:09",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Explosion",
    nickname: "towers",
    time: "2:25",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Burn Mark",
    nickname: "double TB",
    time: "2:26",
    phase: 1,
    subphase: "Towers",
  },
  {
    name: "Quadruple Slap",
    nickname: "TB",
    time: "2:51",
    additionalHitsAt: ["2:55"],
    phase: 2,
    subphase: "P2 Opener",
  },
  {
    name: "Diamond Dust",
    nickname: "castbar",
    time: "3:11",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "The House of Light",
    nickname: "cones",
    time: "3:21",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Frigid Stone",
    nickname: "stars",
    time: "3:23",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Heavenly Strike",
    nickname: "KB",
    time: "3:27",
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Sinbound Holy",
    nickname: "stack puddles",
    time: "3:31",
    additionalHitsAt: ["3:33", "3:34", "3:36"],
    phase: 2,
    subphase: "Diamond Dust",
  },
  {
    name: "Hallowed Ray",
    nickname: "line stack",
    time: "3:59",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "The House of Light",
    nickname: "proteans",
    time: "4:23",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "The House of Light",
    nickname: "proteans",
    time: "4:33",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "Banish III",
    nickname: "stack/spread",
    time: "4:39",
    phase: 2,
    subphase: "Mirror, Mirror",
  },
  {
    name: "Light Rampant",
    nickname: "castbar",
    time: "4:48",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Luminous Hammer",
    nickname: "puddles",
    time: "4:56",
    additionalHitsAt: ["4:58", "4:59", "5:01", "5:02"],
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Bright Hunger",
    nickname: "towers",
    time: "4:59",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Powerful Light",
    nickname: "stacks",
    time: "5:05",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Bright Hunger",
    nickname: "2s tower",
    time: "5:14",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Banish III",
    nickname: "stack/spread",
    time: "5:17",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "The House of Light",
    nickname: "proteans",
    time: "5:26",
    phase: 2,
    subphase: "Light Rampant",
  },
  {
    name: "Absolute Zero",
    nickname: "phase ender",
    time: "5:45",
    phase: 2,
    subphase: "P2 Enrage",
  },
];
